name: Nix Installer
description: Nix Installer

inputs:
  cache-unique-id:
    description: Unique ID to differentiate caches
    required: true

outputs:
  cache-hit:
    description: Whether the cache was restored or not
    value: ${{ steps.nix-restore-and-save.outputs.cache-hit == 'true' || steps.nix-restore.outputs.cache-hit == 'true' }}

runs:
  using: composite
  steps:
    - name: Restore and Save Cache
      id: nix-restore-and-save
      if: ${{ github.event_name == 'schedule' }}
      uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: /tmp/nix-cache
        key: nix-cache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ inputs.cache-unique-id }}-${{ hashFiles('**/flake.lock') }}

    - name: Restore Cache
      id: nix-restore
      if: ${{ github.event_name != 'schedule' }}
      uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: /tmp/nix-cache
        key: nix-cache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ inputs.cache-unique-id }}-${{ hashFiles('**/flake.lock') }}

    - name: Restore Cached Path
      if: ${{ steps.nix-restore-and-save.outputs.cache-hit == 'true' || steps.nix-restore.outputs.cache-hit == 'true' }}
      shell: bash
      run: |
        set -ex
        sudo mkdir -p /nix
        sudo chown -R "${USER}:" /nix

        sudo mkdir -p /etc/nix
        echo "extra-experimental-features = flakes nix-command" > nix.conf
        sudo mv nix.conf /etc/nix/nix.conf

        # Restore nix directories from cache
        if [ -d /tmp/nix-cache/store ]; then
          sudo cp -r /tmp/nix-cache/store /nix/
        fi
        
        if [ -d /tmp/nix-cache/var ]; then
          sudo cp -r /tmp/nix-cache/var /nix/
        fi

        echo "/nix/var/nix/profiles/per-user/root/profile/bin" >> $GITHUB_PATH
        echo "/nix/var/nix/profiles/default/bin" >> $GITHUB_PATH

        sudo chown -R "${USER}:" /nix

    - name: Install Nix If There Is No Cache
      if: ${{ steps.nix-restore-and-save.outputs.cache-hit != 'true' && steps.nix-restore.outputs.cache-hit != 'true' }}
      uses: DeterminateSystems/nix-installer-action@3ebd1aebb47f95493b62de6eec0cac3cd74e50a9
