name: Nix Cache
description: Cache Nix File To Temporary Directory

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo systemctl stop nix-daemon
        sudo chown -R "${USER}:" /nix

        sudo mkdir -p /tmp/nix-cache/store \
          && sudo cp -r /nix/store /tmp/nix-cache/store

        sudo mkdir -p /tmp/nix-cache/var/nix/db \
          && sudo cp -r /nix/var/nix/db /tmp/nix-cache/var/nix/db

        sudo mkdir -p /tmp/nix-cache/var/nix/profiles \
          && sudo cp -r /nix/var/nix/profiles /tmp/nix-cache/var/nix/profiles

        sudo rm -rf /nix
