name: Nix Cache
description: Cache Nix File To Temporary Directory

inputs:
  cache-unique-id:
    description: Unique ID to differentiate caches
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        sudo systemctl stop nix-daemon
        sudo chown -R "${USER}:" /nix

        # Create cache directory and copy nix store contents
        sudo mkdir -p /tmp/nix-cache

        # Copy store contents directly to cache root
        if [ -d /nix/store ]; then
          sudo cp -r /nix/store /tmp/nix-cache/
        fi

        # Copy database
        if [ -d /nix/var/nix/db ]; then
          sudo mkdir -p /tmp/nix-cache/var/nix
          sudo cp -r /nix/var/nix/db /tmp/nix-cache/var/nix/
        fi

        # Copy profiles
        if [ -d /nix/var/nix/profiles ]; then
          sudo mkdir -p /tmp/nix-cache/var/nix
          sudo cp -r /nix/var/nix/profiles /tmp/nix-cache/var/nix/
        fi

        # Fix permissions so GitHub Actions can archive the files
        sudo chown -R "${USER}:" /tmp/nix-cache

        sudo rm -rf /nix

    - name: Save Cache
      uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684
      with:
        path: /tmp/nix-cache
        key: nix-cache-${{ runner.os }}-${{ github.workflow }}-${{ github.job }}-${{ inputs.cache-unique-id }}-${{ hashFiles('**/flake.lock') }}
