name: Copilot

permissions:
  contents: read

on:
  push:
    paths:
      - .github/workflows/copilot.yml
  pull_request:
    paths:
      - .github/workflows/copilot.yml
  workflow_dispatch:
    inputs:
      commit_sha:
        description: Git commit sha, on which, to run this workflow

defaults:
  run:
    shell: nix develop ./tools/nix --command bash {0}

jobs:
  copilot-setup-steps:
    name: Copilot - setup
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: ${{ github.event.inputs.commit_sha }}

      - name: Setup Nix
        id: setup-nix
        uses: ./.github/actions/setup_nix
        with:
          cache-id: all
